### ISSUE TITLE
Combining entity wise results into data set wise results

### ISSUE THREAD

**Issue by jules-samaran** [NetManAIOps/OmniAnomaly#17]
Dear authors,
in your paper you report results for SMAP, MSL and SMD however the anomaly detection is done at the entity level. Could you explain how you obtained precision, recall and f1 score for the whole data sets from the anomaly predictions you had for each of the entities that composed the data sets?
Best

**Comment by gorold** [comment]
Dear authors, is there any update for this? I would also like to know, especially for the SMD dataset, how the f1 score is combined from each machine-i-j into a single score? Is the simple average of f1 taken over all the datasets? Or do you use the total TP/TN/FP/FN to calculate?

**Comment by raimishah** [comment]
did you figure this out?

**Comment by TsingHuasuya** [comment]
> total TP/TN/FP/FN to calculate

 We use the total TP/TN/FP/FN to calculate the overall results for data sets

**Comment by TsingHuasuya** [comment]
> Dear authors,
> in your paper you report results for SMAP, MSL and SMD however the anomaly detection is done at the entity level. Could you explain how you obtained precision, recall and f1 score for the whole data sets from the anomaly predictions you had for each of the entities that composed the data sets?
> Best

 We use the total TP/TN/FP/FN to calculate the overall results for data sets
