### ISSUE TITLE
Possible leak from the test set for POT

### ISSUE THREAD

**Issue by selimfirat** [NetManAIOps/OmniAnomaly#19]
Dear authors, 

Thank you for sharing this work.

I tried random numbers from the normal distribution with mean 0 and std 0.1 as model scores and evaluated using the pot_eval function. The best-f1 score seems fine, yet, the pot-f1 score seems buggy. 

I attached main_random.py to reproduce the results.
[main_random.txt](https://github.com/NetManAIOps/OmniAnomaly/files/4944752/main_random.txt)
Github does not allow uploading .py, thus, rename main_random.txt to main_random.py and place it on the main directory. The installation is the same with this project.

For the MSL dataset,
best-f1:  0.3184
pot-f1: 0.8987 (The score in paper is 0.8989 in Table 3)
To reproduce, run `python main_random.py --dataset='MSL'`. 

For the SMAP dataset,
best-f1: 0.3691
pot-f1: 0.9610 (The score in the paper is 0.8434 in Table 3)
To reproduce, run `python main_random.py --dataset='SMAP'`

These pot-f1 scores are higher than the ones in the paper. If I am not doing anything wrong, the results indicate that there is a leak from the for the POT method and its corresponding scores in the paper. Issue #15 also seems related.

May you help to explain why this happens? Thank you.

**Comment by TsingHuasuya** [comment]
> Dear authors,
> 
> Thank you for sharing this work.
> 
> I tried random numbers from the normal distribution with mean 0 and std 0.1 as model scores and evaluated using the pot_eval function. The best-f1 score seems fine, yet, the pot-f1 score seems buggy.
> 
> I attached main_random.py to reproduce the results.
> [main_random.txt](https://github.com/NetManAIOps/OmniAnomaly/files/4944752/main_random.txt)
> Github does not allow uploading .py, thus, rename main_random.txt to main_random.py and place it on the main directory. The installation is the same with this project.
> 
> For the MSL dataset,
> best-f1: 0.3184
> pot-f1: 0.8987 (The score in paper is 0.8989 in Table 3)
> To reproduce, run `python main_random.py --dataset='MSL'`.
> 
> For the SMAP dataset,
> best-f1: 0.3691
> pot-f1: 0.9610 (The score in the paper is 0.8434 in Table 3)
> To reproduce, run `python main_random.py --dataset='SMAP'`
> 
> These pot-f1 scores are higher than the ones in the paper. If I am not doing anything wrong, the results indicate that there is a leak from the for the POT method and its corresponding scores in the paper. Issue #15 also seems related.
> 
> May you help to explain why this happens? Thank you.

In our evaluations, we have repeated the experiments many times, and there indeed have high and low result, because the model training and anomaly scores are not very stable for each experiment.
