### ISSUE TITLE
Request: tfsnippet version in requirements.txt  not available 

### ISSUE THREAD

**Issue by opooladz** [NetManAIOps/OmniAnomaly#20]
Hello, 

Thank you for this repo. 
It seems the version of the [repo](https://github.com/haowen-xu/tfsnippet.git@v0.2.0-alpha1) required for the OmniAnomaly repo is no longer available. Can you kindly host the v0.2.0-alpha1 of the tfsnippet repo or send via email? opooladz at ucla dot edu

Thank you in advance

**Comment by chrisby** [comment]
Any updates on this?

**Comment by chrisby** [comment]
> Any updates on this?

OK, I saw it was updated.
