### ISSUE TITLE
Problem with training parameters about SMAP and MSL.

### ISSUE THREAD

**Issue by JinchuanZ** [NetManAIOps/OmniAnomaly#21]
Dear Author,
In your paper and the project, I can see the different parameter“level” with SMAP = 0.07 and MSL = 0.01.
Can you tell me the other different parameters setting about the two datasets training?
Thanks.

**Comment by TsingHuasuya** [comment]
> Dear Author,
> In your paper and the project, I can see the different parameter“level” with SMAP = 0.07 and MSL = 0.01.
> Can you tell me the other different parameters setting about the two datasets training?
> Thanks.

The other parameters for these two datasets are all the same, and you can refer them in the codes
