### ISSUE TITLE
What is the exactly meaning of each column of the 38 columns of SMD

### ISSUE THREAD

**Issue by wardenjohn** [NetManAIOps/OmniAnomaly#22]
I am now get your Server Machine Dataset. As written in your paper, there are CPU load , network usage, memory usage record for each machine record. But there is no information of each column and I am now trying to use this dataset for analysis. What's more, is each row sampled in a equal time intervals? Thanks!

**Comment by TsingHuasuya** [comment]
> I am now get your Server Machine Dataset. As written in your paper, there are CPU load , network usage, memory usage record for each machine record. But there is no information of each column and I am now trying to use this dataset for analysis. What's more, is each row sampled in a equal time intervals? Thanks!

cpu_r,load_1,load_5,load_15,mem_shmem,mem_u,mem_u_e,total_mem,disk_q,disk_r,disk_rb,disk_svc,disk_u,disk_w,disk_wa,disk_wb,si,so,eth1_fi,eth1_fo,eth1_pi,eth1_po,tcp_tw,tcp_use,active_opens,curr_estab,in_errs,in_segs,listen_overflows,out_rsts,out_segs,passive_opens,retransegs,tcp_timeouts,udp_in_dg,udp_out_dg,udp_rcv_buf_errs,udp_snd_buf_errs
Yes, each row is sampled in the same time interval.

**Comment by JinYang88** [comment]
Could you please give more concrete description about the KPI? For example, what is the difference of mem_u and mem_u_e? What is eth1_fi?

Thanks !
