### ISSUE TITLE
Implemented model architecture does not match the paper

### ISSUE THREAD

**Issue by viliket** [NetManAIOps/OmniAnomaly#23]
In your paper (Robust anomaly detection for multivariate time series through stochastic recurrent neural network) in Figure 3 b1 you describe the network architecture of **qnet**, which begins as follows:

<img src="https://render.githubusercontent.com/render/math?math=x_t"> -> GRU -> <img src="https://render.githubusercontent.com/render/math?math=e_t"> (GRU hidden output) -> concatenate <img src="https://render.githubusercontent.com/render/math?math=e_t"> with <img src="https://render.githubusercontent.com/render/math?math=z_{t-1}"> -> Dense layer <img src="https://render.githubusercontent.com/render/math?math=h^\phi"> -> ...

However, the implemented code does not follow this architecture:

After the RNN cell, you immediately put the RNN's hidden output <img src="https://render.githubusercontent.com/render/math?math=e_t"> through (two) **linear** layers:

wrapper.py (lines 113-120)
```
try:
    outputs, _ = rnn.static_rnn(fw_cell, x, dtype=tf.float32)
except Exception:  # Old TensorFlow version only returns outputs not states
    outputs = rnn.static_rnn(fw_cell, x, dtype=tf.float32)
outputs = tf.stack(outputs, axis=time_axis)
for i in range(hidden_dense):
    outputs = tf.layers.dense(outputs, dense_dim)
return outputs
```
So this code shows first issue:

As you are not specifying the activation type in tf.layers.dense() function, these layers have linear activation, not ReLU as you claim in the paper. Also, did you use hidden_dense=2 in the experiments described in the paper or was it 1?

Second:

In the paper you say that you concatenate <img src="https://render.githubusercontent.com/render/math?math=e_t"> with <img src="https://render.githubusercontent.com/render/math?math=z_t"> and after that apply a dense layer with ReLU activation, which is not done in your implementation:

recurrent_distribution.py (lines 43-46):
```
input_q = tf.concat([input_q_n, z_previous], axis=-1)
mu_q = self.mean_q_mlp(input_q, reuse=tf.AUTO_REUSE)  # n_sample * batch_size * z_dim

std_q = self.std_q_mlp(input_q)  # n_sample * batch_size * z_dim
```

The code above show that the concatenated output is directly given to mu and std layers, not to a dense layer with ReLU activation before this.

So what your current implementation does in the **qnet** is more like following:
<img src="https://render.githubusercontent.com/render/math?math=x_t"> -> GRU -> <img src="https://render.githubusercontent.com/render/math?math=e_t"> (GRU hidden output) -> x (two?) linear layers -> concatenate <img src="https://render.githubusercontent.com/render/math?math=e_t"> with <img src="https://render.githubusercontent.com/render/math?math=z_{t-1}"> -> Get mu and std using the concatenation as an input for the mu layer and std layer -> ...

What is the reason for this difference in the actual implementation and the one described in the original paper? Which architecture was used in the experiments reported in the paper?

**Comment by TsingHuasuya** [comment]
> In your paper (Robust anomaly detection for multivariate time series through stochastic recurrent neural network) in Figure 3 b1 you describe the network architecture of **qnet**, which begins as follows:
> 
> ![](https://render.githubusercontent.com/render/math?math=x_t) -> GRU -> ![](https://render.githubusercontent.com/render/math?math=e_t) (GRU hidden output) -> concatenate ![](https://render.githubusercontent.com/render/math?math=e_t) with ![](https://render.githubusercontent.com/render/math?math=z_{t-1}) -> Dense layer ![](https://render.githubusercontent.com/render/math?math=h^\phi) -> ...
> 
> However, the implemented code does not follow this architecture:
> 
> After the RNN cell, you immediately put the RNN's hidden output ![](https://render.githubusercontent.com/render/math?math=e_t) through (two) **linear** layers:
> 
> wrapper.py (lines 113-120)
> 
> ```
> try:
>     outputs, _ = rnn.static_rnn(fw_cell, x, dtype=tf.float32)
> except Exception:  # Old TensorFlow version only returns outputs not states
>     outputs = rnn.static_rnn(fw_cell, x, dtype=tf.float32)
> outputs = tf.stack(outputs, axis=time_axis)
> for i in range(hidden_dense):
>     outputs = tf.layers.dense(outputs, dense_dim)
> return outputs
> ```
> 
> So this code shows first issue:
> 
> As you are not specifying the activation type in tf.layers.dense() function, these layers have linear activation, not ReLU as you claim in the paper. Also, did you use hidden_dense=2 in the experiments described in the paper or was it 1?
> 
> Second:
> 
> In the paper you say that you concatenate ![](https://render.githubusercontent.com/render/math?math=e_t) with ![](https://render.githubusercontent.com/render/math?math=z_t) and after that apply a dense layer with ReLU activation, which is not done in your implementation:
> 
> recurrent_distribution.py (lines 43-46):
> 
> ```
> input_q = tf.concat([input_q_n, z_previous], axis=-1)
> mu_q = self.mean_q_mlp(input_q, reuse=tf.AUTO_REUSE)  # n_sample * batch_size * z_dim
> 
> std_q = self.std_q_mlp(input_q)  # n_sample * batch_size * z_dim
> ```
> 
> The code above show that the concatenated output is directly given to mu and std layers, not to a dense layer with ReLU activation before this.
> 
> So what your current implementation does in the **qnet** is more like following:
> ![](https://render.githubusercontent.com/render/math?math=x_t) -> GRU -> ![](https://render.githubusercontent.com/render/math?math=e_t) (GRU hidden output) -> x (two?) linear layers -> concatenate ![](https://render.githubusercontent.com/render/math?math=e_t) with ![](https://render.githubusercontent.com/render/math?math=z_{t-1}) -> Get mu and std using the concatenation as an input for the mu layer and std layer -> ...
> 
> What is the reason for this difference in the actual implementation and the one described in the original paper? Which architecture was used in the experiments reported in the paper?

We have fine-tuned the structure of the model when deploying in the enterprise for better result. The experiments reported in the paper used our codes.
