### ISSUE TITLE
requesting an open-source license (eg. MIT)

### ISSUE THREAD

**Issue by astha-chem** [NetManAIOps/OmniAnomaly#24]
Thanks for the great work. Have you considered adding a license to your code so that people can reuse the code, modify it and distribute?

Github's default license is that no one has the right to reuse, modify or redistribute your code - https://choosealicense.com/no-permission/ unless you choose a different open-source license (such as MIT).

**Comment by vafl** [comment]
:+1: 

It would be wonderful if you could add a licence. Thanks for the great work!

**Comment by TsingHuasuya** [comment]
I have added a MIT license to this github repo.

**Comment by TsingHuasuya** [comment]
> Thanks for the great work. Have you considered adding a license to your code so that people can reuse the code, modify it and distribute?
> 
> Github's default license is that no one has the right to reuse, modify or redistribute your code - https://choosealicense.com/no-permission/ unless you choose a different open-source license (such as MIT).

I have added a MIT license to my github repo.

**Comment by TsingHuasuya** [comment]
> 👍
> 
> It would be wonderful if you could add a license. Thanks for the great work!

I have added a MIT license to my github repo.
