### ISSUE TITLE
SMD Dataset - Default settings same as results reported in paper?

### ISSUE THREAD

**Issue by gorold** [NetManAIOps/OmniAnomaly#27]
Hi authors,

I am trying to replicate the results reported in your paper. I would like to confirm whether the default hyperparameter settings provided in the code are exactly the same as the experiments you reported in your paper?

I think another issue I'm having in replicating similar Pot-F1 scores is the issue mentioned in #17, how do you combine the Pot-F1 from 28 different entities into a single score? I have attached the results I by running the code: [omnianom_results.txt](https://github.com/NetManAIOps/OmniAnomaly/files/5508939/omnianom_results.txt).

Thank you!

**Comment by TsingHuasuya** [comment]
> Hi authors,
> 
> I am trying to replicate the results reported in your paper. I would like to confirm whether the default hyperparameter settings provided in the code are exactly the same as the experiments you reported in your paper?
> 
> I think another issue I'm having in replicating similar Pot-F1 scores is the issue mentioned in #17, how do you combine the Pot-F1 from 28 different entities into a single score? I have attached the results I by running the code: [omnianom_results.txt](https://github.com/NetManAIOps/OmniAnomaly/files/5508939/omnianom_results.txt).
> 
> Thank you!

The settings provided in the code are not reported in my paper due to limited space.

**Comment by TsingHuasuya** [comment]
> Hi authors,
> 
> I am trying to replicate the results reported in your paper. I would like to confirm whether the default hyperparameter settings provided in the code are exactly the same as the experiments you reported in your paper?
> 
> I think another issue I'm having in replicating similar Pot-F1 scores is the issue mentioned in #17, how do you combine the Pot-F1 from 28 different entities into a single score? I have attached the results I by running the code: [omnianom_results.txt](https://github.com/NetManAIOps/OmniAnomaly/files/5508939/omnianom_results.txt).
> 
> Thank you!

In our evaluations, we have repeated the experiments many times, and there indeed have high and low result, because the model training and anomaly scores are not very stable for each experiment
